### ISSUE TITLE
Prázdne foldre

### ISSUE THREAD

**Issue by Gummak** [kodi-czsk/plugin.video.markiza.sk#17]
Ahoj.
Asi doslo k zmene na webe kvoli ktorej nezobrazí nič na prehrávanie.

T

**Comment by jose1711** [comment]
ak chces/mas moznost, otestuj tento fork: https://github.com/jose1711/plugin.video.markiza.sk

**Comment by martinstefany** [comment]
Posielam poďakovanie (môžem pozerať Dobre vedieť!) a pochvalu - vyzerá, že funguje :)
