### ISSUE TITLE
Prázdny priečinok

### ISSUE THREAD

**Issue by nitram1222** [kodi-czsk/plugin.video.markiza.sk#21]
Doplnok nefunguje,prázdne foldre

**Comment by mukates** [comment]
Opravene vo verzii 1.2.0...
https://github.com/mx3L/archivczsk-doplnky/tree/master/xbmc-doplnky/repo/plugin.video.markiza.sk

**Comment by mYrecc** [comment]
Stále nefunkčné aj vo verzii 1.2.0

**Comment by mukates** [comment]
U mna 1.2.0 funguje. Tak neviem...

**Comment by orefmi** [comment]
Nefunkcne pod Windows7 -  Kodi 17.6 Krypton, vecer vyskusam na LibreELEC.
Velka vdaka za stalu podporu.

**Comment by nitram1222** [comment]
Mne zatiaľ ukazuje že posledná verzia je 1.9.0 na kodi na tel a aj na Liberec na Raspberry,dám update tak stále je len 1.9.0 verzia a tam to nejde .

**Comment by orefmi** [comment]
ver.1.2.0 v prilohe

ut 11. 9. 2018 o 13:00 nitram1222 <notifications@github.com> napísal(a):

**Comment by mukates** [comment]
Na androidboxe (android) 7.0.1 s kodi 17.6 neide ani 1.2.0 Hadze chybu doplnku :-(

**Comment by nitram1222** [comment]
Na tel pixel 2 (Android 9 verzia) kodi 17.6 ,doplnok 1.2.0 Markíza vyhradzuje chybu hneď po kliknutí na doplnok (Markíza.sk error , check the log for more information)

**Comment by jdemovic** [comment]
Win10 64, 17.6, 1.2.0 - nejde

**Comment by janvalentik** [comment]
Raspberry, Libreelec 8.2.5, Kodi Krypton 17.6, Markiza.sk 1.2.0 taktéž vyhodí chybu doplňku. Pokud by se podařilo opravit, tak by to bylo super, manželka mě bombarduje, že nemůže koukat na turecké seriály.

Díky za podporu

**Comment by koperfieldcz** [comment]
Uvědomte si, že zde uvedený plugin je vytvořen pro Enigma2. Proto je třeba jej upravit pro Kodi. Plugin vyhazuje chybu z toho důvodu, že má importovat archivczsk (repozitář pro E2), který nemá odkud brát (nepokoušejte se jej instalovat, nepomůžete si). Musíte si počkat, až to někdo přepíše.

**Comment by koperfieldcz** [comment]
Po zbytečném laborování mám fix. PR je přidáno, pro nedočkavce je plugin zde:
https://github.com/koperfieldcz/plugin.video.markiza.sk/releases/download/1.2.0/plugin.video.markiza.sk-1.2.0.zip
Určitě se ještě musí vyladit Televízne noviny, protože se nezobrazuje datum. To už přenechám dalším. Každopádně vše funguje. Alespoň po mém testu.

**Comment by nitram1222** [comment]
Vďaka za opravu ,funguje  keď som ho len tak na rýchlo skúsil na Pixel 2 (Android 9.0) Kodi 17.6

**Comment by janvalentik** [comment]
Díky moc.
