### ISSUE TITLE
Chyba skriptu na MINIX s XBMC 14.0-ALPHA4

### ISSUE THREAD

**Issue by housaj** [kodi-czsk/plugin.video.markiza.sk#3]
Při spuštění doplňku ohlásí systém "chyba scriptu"
Spouštěno na MINIX NEO Z64A s Android 4.4.4

**Comment by mx3L** [comment]
Ak je to este aktualne tak poprosim o log

**Comment by jose1711** [comment]
uz je asi na case to zavriet..
