### ISSUE TITLE
nefunguje: Zamena manzeliek

### ISSUE THREAD

**Issue by kalikadze** [kodi-czsk/plugin.video.markiza.sk#31]
caute, 
neviem, ci to robi iba mne, ale nefunguje mi napr relacia Zamena manzeliek. 
Ine som neskusal. Vypise chybu addonu.

Dakujem.
Pekny den

**Comment by rywko** [comment]
Cau,
Relacia nefunguje ani cez prehliadac. Po jej vybere sa zobrazi chyba https://videoarchiv.markiza.sk/video/zamena-manzeliek

**Comment by kalikadze** [comment]
Prepac, mas pravdu, ja som si to neoveril. Dakujem.
