### ISSUE TITLE
nejdou epizody

### ISSUE THREAD

**Issue by ppazda** [kodi-czsk/plugin.video.markiza.sk#32]
Nejdou  v archivu markiza sk posledni epizody farma 11 porat s tim laboruji a stale to nejde je to jen u farmy posledni dily

**Comment by MK87** [comment]
Jdou! Musis mit SK IP pak to jde v pohode. Taky jsem si vsimnul, ze mi to nejde (asi 5dilu nazpet) tak jsem zkusil v Kodi slovenskou VPN a bez problemu!

**Comment by ppazda** [comment]
Super a prosím kde vezmu si VPN

**Comment by rywko** [comment]
Nejde o chybu pluginu. Ak vam nefunguje prehravanie z vasej IP adresy cez prehliadac na PC/mobile, plugin tiez narazi pri spracovavani stranky na rovnaku chybu
