### ISSUE TITLE
Markiza live

### ISSUE THREAD

**Issue by mrgfx** [kodi-czsk/plugin.video.markiza.sk#37]
Dobry, prosim vas, vedeli by ste pridat funkciu live prenosu? Kedze Markiza zverejnuje live prenos na ich webe, bolo by to zrejme bolo mozne.
https://videoarchiv.markiza.sk/live/1-markiza
https://videoarchiv.markiza.sk/live/3-doma
https://videoarchiv.markiza.sk/live/2-dajto
Pripadne by sa dalo z ich stranky zistit m3u subor, aby sa dal pouzit v iptv?
Dakujem

**Comment by rywko** [comment]
Dobry den, funkcia bola pridana
 V nastaveniach je potrebne zadat prihlasovacie udaje zo stranky moja.markiza.sk. Bez cookies nie je mozne priamo pouzit m3u subor (server vrati chybu 403)

**Comment by mrgfx** [comment]
Dobry, prepacne som v kodi zaciatocnik. Ked dam updatovat markiza addon, mam verziu 1.3.7 ale nevidim ani len moznost nastaveni. Treba stiahmut niaku specialnu verziu tochto addonu?

**Comment by rywko** [comment]
Nova verzia je uz dostupna v novom CZSK repozitari 
`https://repo.xbmc-kodi.cz/`
V tomto repozitari bude dostupna po schvaleni pull requestu #38

**Comment by mrgfx** [comment]
Ďakujem Vám veľmi pekne.
