### ISSUE TITLE
Error v archíve

### ISSUE THREAD

**Issue by nitram1222** [kodi-czsk/plugin.video.markiza.sk#41]
Po kliknutí na hocijakú reláciu alebo seriál vyskočí error a neprehrá nič .live funguje dobre len archív nejde.

**Comment by rywko** [comment]
Oprava dostupna v #42

**Comment by rgabera** [comment]
Tu je opravený repozitár podľa navodu vyššie (rywko - oprava dostupna v 42)
[https://ulozto.sk/file/jfvSZfTL96OF/plugin-kodi-video-markiza-sk-zip]
