### ISSUE TITLE
Chyba přehrávání

### ISSUE THREAD

**Issue by janvalentik** [kodi-czsk/plugin.video.markiza.sk#43]
Zdravím, předem chci poděkovat za vaší práci na pluginu. Mám ale problém s přehráváním některých věcí. Například turecké seriály. Žena do mě stále hučí, že proč zrovna tohle nejde. 
při pokusu o přehrání epizody vyhodí chybu s tím, že více info v protokolu. Do protokolu se ale nic nezapíše. Pokud by někdo věděl jak to opravit, tak bych byl vděčný.

**Comment by rywko** [comment]
Dobry den. Do novej verzie som pridal dve nove chybove hlasky, ktore by vam mohli pomoct pri rieseni problemu. Myslim si, ze problem je sposobenym obmedzenim na slovenske adresy. Skuste, ci vam problemove relacie funguju cez webovy prehliadac

Duplicate of #32

**Comment by janvalentik** [comment]
Máte pravdu. Je to tím. Zkusím pohledat nějakou VPN, ale co jsem tak koukal, taky ty zdarma vetšinou nic moc a placenou se mi zrovna kvůli tureckým patlaninám moc dávat nechce.

Každopádně vám děkuji.

**Comment by rywko** [comment]
Dobry vecer, mozete prosim potvrdit, ze v najnovsej verzii pluginu sa pri vyskyte tohto problemu zobrazi chybove hlasenie 'Video nie je dostupné vo vašej krajine'? Nemal som moznost otestovat funkcnost tejto zmeny zo zahranicia.

**Comment by janvalentik** [comment]
Dobrý den, bohužel vyskakuje stále jen hláška o více info v logu. https://ctrlv.cz/K4YQ

Verze 1.3.11

**Comment by rywko** [comment]
Ano, este boli potrebne upravy. Novu verziu 1.3.12 som otestoval cez CZ VPN. Chybova hlaska by sa vam uz mala riadne zobrazit.

**Comment by janvalentik** [comment]
Ano, nyní už to správně zobrazuje hlášku o nedostupnosti v krajině. Děkuji
