### ISSUE TITLE
Chyba prehravania

### ISSUE THREAD

**Issue by mukates** [kodi-czsk/plugin.video.markiza.sk#5]
Ahojte. Plugin mi prestal fungovat. Ak chcem cokolvek prehrat, dostanem iba hlasku: "Chyba. Prehravanie jednej, alebo viacerych poloziek zlyhalo". donedavna vsetko fungovalo bez problemov.

**Comment by rehvenge** [comment]
Postupně mi tento týden přestával přehrávat pořady, teď už nic. Port 1935, na který se doplněk dotazuje je zavřený. Vypadá to, že na portu 80 by to mohlo poslouchat.

**Comment by mx3L** [comment]
Ahojte, ano je to tak @rehvenge, opravene v 1.0.7

**Comment by rehvenge** [comment]
Updatovala jsem plugin na verzi 1.0.7, nicméně stále to má problémy, například nové díly MasterChef a Farmy.  
Pomůže kus logu?
21:35:39 T:2304  NOTICE: ["Initializing provider videoarchiv.markiza.sk with settings {'downloads': '', 'quality': '1'}"]
21:35:39 T:2304  NOTICE: ['filtering by quality setting 1']
21:35:39 T:1904  NOTICE: DVDPlayer: Opening: http://cdn.srv.markiza.sk/vod/_definst_/smil:part/X0ptOxVWTPukbfqdwNJnYcYVNMMNof48.smil/manifest.m3u8
21:35:39 T:1904 WARNING: CDVDMessageQueue(player)::Put MSGQ_NOT_INITIALIZED
21:35:39 T:4808  NOTICE: Creating InputStream
21:35:39 T:4808  NOTICE: Creating Demuxer
21:35:39 T:4808   ERROR: CCurlFile::GetCookies - invalid cookie:.......
......
21:35:42 T:4808   ERROR: CDVDPlayer::OpenDemuxStream - Error creating demuxer
21:35:42 T:4808  NOTICE: CDVDPlayer::OnExit()
21:35:42 T:1904   ERROR: Playlist Player: skipping unplayable item: 0, path [plugin://plugin.video.markiza.sk/?play=2f766964656f2f6d6173746572636865662f34353330385f6d6173746572636865662d3131&cp=766964656f6172636869762e6d61726b697a612e736b&]
21:35:42 T:1904  NOTICE: CDVDPlayer::CloseFile()
21:35:42 T:1904  NOTICE: DVDPlayer: waiting for threads to exit
21:35:42 T:1904  NOTICE: DVDPlayer: finished waiting
21:35:42 T:1904  NOTICE: CDVDPlayer::CloseFile()
21:35:42 T:1904  NOTICE: DVDPlayer: waiting for threads to exit
21:35:42 T:1904  NOTICE: DVDPlayer: finished waiting
21:35:42 T:4464 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.markiza.sk/?play=2f766964656f2f6d6173746572636865662f34363135305f6d6173746572636865662d3134&cp=766964656f6172636869762e6d61726b697a612e736b&
21:35:42 T:3292 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.markiza.sk/?play=2f766964656f2f6d6173746572636865662f34363035355f6d6173746572636865662d3133&cp=766964656f6172636869762e6d61726b697a612e736b&
21:35:42 T:3292 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.markiza.sk/?play=2f766964656f2f6d6173746572636865662f34353330375f6d6173746572636865662d3132&cp=766964656f6172636869762e6d61726b697a612e736b&
21:35:42 T:2796 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.markiza.sk/?play=2f766964656f2f6d6173746572636865662f34353330385f6d6173746572636865662d3131&cp=766964656f6172636869762e6d61726b697a612e736b&
21:35:42 T:2796 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.markiza.sk/?play=2f766964656f2f6d6173746572636865662f34353330335f6d6173746572636865662d3130&cp=766964656f6172636869762e6d61726b697a612e736b&
21:35:42 T:2796 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.markiza.sk/?play=2f766964656f2f6d6173746572636865662f34353330345f6d6173746572636865662d3039&cp=766964656f6172636869762e6d61726b697a612e736b&
21:35:42 T:2796 WARNING: XFILE::CFileFactory::CreateLoader - unsupported protocol(plugin) in plugin://plugin.video.markiza.sk/?play=2f766964656f2f6d6173746572636865662f34343735355f6d6173746572636865662d3038&cp=766964656f6172636869762e6d61726b697a612e736b&
21:35:42 T:4312  NOTICE: 1Channel: Service: Playback Stopped
21:35:42 T:1976  NOTICE: Stream All The Sources: Service: Playback Stopped

**Comment by mx3L** [comment]
@rehvenge
A cez web prehravanie funguje?
http://videoarchiv.markiza.sk/video/masterchef

Skusal som prehrat link priamo z logu cez vlc a funguje. Takisto som otestoval MasterChef casti 14, 15 v Kodi-16.1 a vsetko funkcne.

**Comment by rehvenge** [comment]
Zkousela jsem Svokru pres Kodi, ta už funguje. Prehrat link MasterChefa z logu pres VLC nefunguje. A ani z archivu...Takze to vypada, na coz jsem mela podezreni, ze nejake programy jsou z CZ zakazane. Asi novinka.  Nicmene, diky za opravu.
