### ISSUE TITLE
Chyba v prehravani 

### ISSUE THREAD

**Issue by nitram1222** [kodi-czsk/plugin.video.markiza.sk#52]
Super doplnok ale uz druhy den ked chcem nieco spustit tak mi zakazdym vyhadzuje chybu,skusal som aj cez VPN a na roznych zariadeniach. Verzia je 1.3.18

**Comment by Najsik** [comment]
Áno pripájam sa, ani mne doplnok nechce nič prehrať

**Comment by rywko** [comment]
Oprava dostupna v #53 
Doslo aj k zmene na stranke. Televizne noviny uz nie su rozdelene do samostatnych videi

**Comment by marki555** [comment]
Hehe super, akurat som chcel tiez spravil pull request :)

**Comment by MarekCHG** [comment]
bohuzial uz ani oprava 53 nefunguje :(

**Comment by jose1711** [comment]
dakujem. skoda, ze to tak rozbili. tie rozdelene videa boli super.

**Comment by marki555** [comment]
No minimalne Extremne premeny nejdu teraz ani cez browser, namiesto videa to pise "Ups! Chyba 500. Stránka, ktorú hľadáte, bola zjedená", takze zrejme to maju pokazene priamo v Markize.

**Comment by MarekCHG** [comment]
> No minimalne Extremne premeny nejdu teraz ani cez browser, namiesto videa to pise "Ups! Chyba 500. Stránka, ktorú hľadáte, bola zjedená", takze zrejme to maju pokazene priamo v Markize.

uz to ide...prave to pozeram...

**Comment by Najsik** [comment]
No web Markíza archív funguje ale doplnok nie.
