### ISSUE TITLE
Error: Skontrolujte si prihlasovacie udaje

### ISSUE THREAD

**Issue by freelancerbob** [kodi-czsk/plugin.video.markiza.sk#55]
Od vcera mi vyhadzuje okno: Error, skontrolujte si prihlasovacie udaje. Udaje su urcite OK, nemenil som nic v KODI a ked sa s nimi prihlasujem cez web prehliadac tak vsetko ide OK.

![image](https://user-images.githubusercontent.com/5004421/96266694-39f1f980-0fc7-11eb-8684-f9cf9b273f6e.png)

**Comment by rywko** [comment]
doslo k zmenam na stranke. oprava dostupna v #56

**Comment by freelancerbob** [comment]
Ako tu zmenu aplikujem v kodi ?

**Comment by rywko** [comment]
Nova verzia je uz dostupna v  repozitari. Staci vynutit aktualizaciu doplnkov v Kodi

**Comment by freelancerbob** [comment]
Ok, uz ide, neviem, rano som vsetko updatol a stale neslo. Vsetko funkcne.
