### ISSUE TITLE
Nefunkcna markiza Kodi Matrix

### ISSUE THREAD

**Issue by freelancerbob** [kodi-czsk/plugin.video.markiza.sk#58]
Upgradoval sa mi TV na kodi 19.0 Matrix a vypadli mi niektore pluginy. Nedokazem ich instalnut. Predpokladam ze preto novy kodi bezi na py3 . Je v plane upgrade pluginov ? Vdaka

**Comment by nitram1222** [comment]
Ani mne na NVIDIA Shield po update na Matrix nefunguje Markíza doplnok

**Comment by JurajNyiri** [comment]
Dobrý deň,

doplnok nie je možné povoliť v Kodi 19: Matrix.

Bolo by možné prosím vydať aktualizáciu?

Ďakujem

**Comment by rywko** [comment]
Nova verzia pluginu je dostupna v novom repozitari: https://github.com/xbmc-kodi-cz/plugin.video.markiza.sk
Navod na instalaciu repozitara: https://repo.xbmc-kodi.cz/

**Comment by jose1711** [comment]
Aktualna verzia doplnku funguje v Kodi Nexus, takze zavieram.
