### ISSUE TITLE
Markíza 1.0.7

### ISSUE THREAD

**Issue by Gummak** [kodi-czsk/plugin.video.markiza.sk#7]
Zdravím. Pred dvomi dňami padlo načítavanie relácii z markízy. Prázdne zložky. Napr. Pri ponuke cez dátum zobrazí iba prázdne zložky. Verzia 1.0.7. Jarvis android

**Comment by mx3L** [comment]
Zdravim, ciastocne opravene v 1.0.8, chybaju najnovsie, najsledovanejsie kategorie, snad cez vikend..

**Comment by Gummak** [comment]
Zdravím, podarilo sa? Dostane sa 1.0.8 aj do repo?

**Comment by mx3L** [comment]
Ahoj, 1.0.8 by mala byt v repo hned po mojej odpovedi, tj. ~8 dni

**Comment by Gummak** [comment]
Zdravím, kontrolujem každý deň. Ale Srrp a kodi cz & Sk majú etale 1.0.7. :-(

**Comment by mx3L** [comment]
@Gummak mas pravdu v repozitary je stale 1.0.7. @lzoubek mozes na to mrknut prosimta?

**Comment by gregi50** [comment]
Prosím o radu. Mám v Kodi nainštalovanú verziu 1.0.8. Zobrazí sa zoznam relácií/seriálov ale po vybratí kontkrétneho seriálu alebo relácie sa nezobrazia žiadne videá ani časti. Dá sa vybrať skrátka len názov ale časti tam už nie sú.  Neviete v čom môže byť problém? Jedná sa mi napr. o archív dobre vedieť. Z ponuky vyberiem reláciu ale nie sú tam žiadne odvysielané časti. Ďakujem za radu prípadne prosím o autora o opravu.

**Comment by mx3L** [comment]
Oprava pridana vo verzii 1.0.9

**Comment by gregi50** [comment]
Verzia 1.0.9 vyskúšaná a funguje. Ďakujem pekne

**Comment by kupony** [comment]
No ja som stiahol 1.09 - nainstaloval som ju zo zipu do kodi 16.1 na android tv, a sice uz opat nacita foldre programov, ale vnutri su tie foldre prazdne, ziadne epizody to nenacitava. Skusil som aj v SPMC na androide a tiez to iste.

**Comment by mx3L** [comment]
Konkretne co nefunguje? napr. som teraz skusil Koleso stastia a nacita.

**Comment by kupony** [comment]
Mne to nenacitalo nic - nacitalo to ten zoznam programov (aj s novymi napr. ta cvernovka alebo ostrov), ale ked kliknem na hocijaky program - nenacita to vobec ziadnu epizodu. Akoze ani jeden ani spravy ani nic. Vymazal som aj cache programov, ze keby nahodou cosi... aj som restartol nexus player ale stale su to len prazdne foldre.

**Comment by mx3L** [comment]
kredenc u mna funguje, poprosim o log

**Comment by mx3L** [comment]
@kupony, z akeho zipu si si ju stiahol?

**Comment by jiro77** [comment]
Ja som tiež aktualizoval z repozitara na verziu 1.0.9 a tiez keď otvorím plugin ukaze mi vsetky relacie atď. ale ak otvorim hoci ktorú z nich, tak tam nič nie je.

**Comment by jiro77** [comment]
Ja som ju stiahol zo zipu: plugin.video.markiza.sk-master

**Comment by jiro77** [comment]
Ja som ju stiahol zo zipu: plugin.video.markiza.sk-master

**Comment by jiro77** [comment]
Ja som ju stiahol zo zipu: plugin.video.markiza.sk-master

**Comment by mx3L** [comment]
A kam si ju rozbalil? Premenoval si adresar po rozbaleni z plugin.video.markiza.sk-master na plugin.video.markiza.sk?
V Kodi vypisuje markiza 1.0.9 verziu?

**Comment by jiro77** [comment]
Nie nerozbalil som ho. Otvoril som Kodi a dal som voľbu nainštalovať zo zip archívu. Vypisalo mi , že plugin sa aktualizoval. A teraz mi ukazuje verziu 1.0.9.

**Comment by jiro77** [comment]
Ani predtým keď som aktualizoval nejaký plugin, tak som ho nerozbaloval a fungovalo to.

**Comment by mx3L** [comment]
Ano malo by to fungovat aj tymto sposobom, poprosim o log

**Comment by jiro77** [comment]
A kde najdem log, kam sa uklada?

**Comment by jiro77** [comment]
Tak už som našiel. Tu je.

07:30:22 T:1729737776  NOTICE: ["Initializing provider videoarchiv.markiza.sk with settings {'downloads': '', 'quality': '1'}"]
07:30:28 T:1748864024  NOTICE: Previous line repeats 1 times.
07:30:28 T:1748864024  NOTICE: ['[videoarchiv.markiza.sk] list - http://videoarchiv.markiza.sk/video/dobre-vediet#categories']
07:30:28 T:1748864024  NOTICE: ['[videoarchiv.markiza.sk] list - detected categories url']
07:30:40 T:1761006928  NOTICE: ["Initializing provider videoarchiv.markiza.sk with settings {'downloads': '', 'quality': '1'}"]
07:30:40 T:1761006928  NOTICE: ['[videoarchiv.markiza.sk] list - http://videoarchiv.markiza.sk/video/koleso-stastia#categories']
07:30:40 T:1761006928  NOTICE: ['[videoarchiv.markiza.sk] list - detected categories url']
07:30:49 T:1764272976  NOTICE: ["Initializing provider videoarchiv.markiza.sk with settings {'downloads': '', 'quality': '1'}"]
07:30:49 T:1764272976  NOTICE: ['[videoarchiv.markiza.sk] list - http://videoarchiv.markiza.sk/video/ohnivy-kure#categories']
07:30:49 T:1764272976  NOTICE: ['[videoarchiv.markiza.sk] list - detected categories url']
07:30:56 T:1753447264  NOTICE: ["Initializing provider videoarchiv.markiza.sk with settings {'downloads': '', 'quality': '1'}"]
07:30:56 T:1753447264  NOTICE: ['[videoarchiv.markiza.sk] list - http://videoarchiv.markiza.sk/video/ostrov#categories']
07:30:56 T:1753447264  NOTICE: ['[videoarchiv.markiza.sk] list - detected categories url']

**Comment by mx3L** [comment]
Prosim odstran nainstalovanu verziu a nainstaluj tuto https://github.com/kodi-czsk/plugin.video.markiza.sk/archive/debug.zip, a pridaj kompletny log subor ako prilohu.

**Comment by bodyguardroman** [comment]
prehravanie funguje:)
Mimochodom tie podsekcie:Najnovšie,Najsledovanejšie doplníš či sa to nebude dať?

**Comment by jiro77** [comment]
Dobré urobil som to. Tu je log.

[log.txt](https://github.com/kodi-czsk/plugin.video.markiza.sk/files/458602/log.txt)

**Comment by mx3L** [comment]
@bodyguardroman 
Ano doplnim

@jiro77 
skus teraz https://github.com/kodi-czsk/plugin.video.markiza.sk/archive/debug.zip

**Comment by mx3L** [comment]
A este vyskusaj ci sa ti stranka zobrazi v prehliadaci: http://videoarchiv.markiza.sk/video/dobre-vediet

**Comment by jiro77** [comment]
Áno stránka sa mi zobrazí v prehliadaci.

**Comment by jiro77** [comment]
Keď som nainstaloval z toho podledneho  zip súboru, tak už to funguje. Zobrazi mi to submenu, ale napriklad v tom archive Dobre vediet nie sú žiadne videá. To asi za to že idú len cez voyo?

**Comment by mx3L** [comment]
Ano presne tak. 
Vdaka za test, oprava pridana vo verzii 1.1.0

**Comment by Gummak** [comment]
Škoda relácie dobre vedieť - obľúbil som si. 

Narazil som ešte na problém s: Tvoja tvár znie povedome.
Raz mi to naskočilo a potom mŕtvo.

Pripájam Log:
[kodi.txt](https://github.com/kodi-czsk/plugin.video.markiza.sk/files/460038/kodi.txt)

**Comment by Gummak** [comment]
Ešte dovysvetlím. Menu až na k celým epizodam je ok. V položke celé epizódy je prázdno.

**Comment by jiro77** [comment]
Áno aj ja som si to vsimol. Verzia 1.1.0 nainstalovaná a v archíve Tvoja tvár znie povedome nacita submenu ale následne všetky položky su prázdne. Na webstranke Markíze v archíve všetko beží.

**Comment by jiro77** [comment]
Funguje to. Vďaka.

**Comment by bodyguardroman** [comment]
aj ostrov kde je polozka cele epizody je to prazdne ale na webe to je.
mimochodom tie podsekcie kedy doplnis?:D

**Comment by jiro77** [comment]
Stiahni si verziu 1.1.1 a pojde ti aj Ostrov.

**Comment by gregi50** [comment]
Je prosím možné nejakým spôsobom nastaviť zložku pre sťahovanie. Ked chcem stiahnuť napríklad prvú epizodu ostrova tak vypíše aby som nastavil zložku pre sťahovanie. Neviem ako to mam urobiť. Ďakujem

**Comment by jiro77** [comment]
Ahoj. To som zasa ja. Dnes som skúšal opraviť tu Markízu u kamosa. Nainstaloval som tam tu verziu 1.1.1 a nejde mu to. Zobrazí mu len "stiahnuté súbory, najnovšie videá a podľa datumu" 
Tu si môžeš pozrieť log:
http://paste.ubuntu.com/23154071/

**Comment by jiro77** [comment]
Tak už to ide. Niekde som asi predtým urobil chybu.

**Comment by gregi50** [comment]
Nik netuší ako si poradiť s tým sťahovaním?

**Comment by mx3L** [comment]
Z markizy nie je mozne stahovat, stahovanie hls streamov nemame implementovane

**Comment by mx3L** [comment]
[B]1.1.2:[/B]
- oprava nacitavania najnovsich videii
- pridane listovanie najnovsich a najsledovanejsich videii
- odstranena nefunkcna moznost stahovat
- odstranene nefunkcna moznost zmeny kvality streamu

Uzatvaram tuto issue kedze je uz vyriesena, takze prosim v pripade problemov vytvorte novu

**Comment by Gummak** [comment]
@ Mx3l: Nádherná práca - reaguješ ako Flash.

Doplnok fičí, tak uzavriem tému. 

Ďakujem za všetkých užívateľov.
